AWSTemplateFormatVersion: '2010-09-09'
Description: "flows gsheets"
Resources:
  modifiedrowFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: modifiedrow
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
  lookuptableFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: lookuptable
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
  modifiedrowLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: modifiedrowFunction
      RetentionInDays: 7
  lookuptableLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: lookuptableFunction
      RetentionInDays: 7
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
  InvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - 321232316075
            - 184705290838
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - lambda:InvokeFunction
              Resource:
              - Fn::GetAtt: [ modifiedrowFunction , Arn ]
              - Fn::GetAtt: [ lookuptableFunction , Arn ]
Outputs:
  modifiedrowFunction:
    Description: 'modifiedrow'
    Value:
      Fn::GetAtt: [ modifiedrowFunction , Arn ]
  modifiedrowRole:
    Description: 'modifiedrow'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  lookuptableFunction:
    Description: 'lookuptable'
    Value:
      Fn::GetAtt: [ modifiedrowFunction , Arn ]
  lookuptableRole:
    Description: 'lookuptable'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
