AWSTemplateFormatVersion: '2010-09-09'
Description: "meshify gsheets"
Resources:
  MESHIFYgsheetsmodifiedrowFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: MESHIFY_gsheets_modifiedrow
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
  MESHIFYgsheetslookuptableFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: MESHIFY_gsheets_lookuptable
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
  MESHIFYgsheetsmodifiedrowLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: MESHIFYgsheetsmodifiedrowFunction
      RetentionInDays: 7
  MESHIFYgsheetslookuptableLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: MESHIFYgsheetslookuptableFunction
      RetentionInDays: 7
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
  InvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - 321232316075
            - 184705290838
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - lambda:InvokeFunction
              Resource:
              - Fn::GetAtt: [ MESHIFYgsheetsmodifiedrowFunction , Arn ]
              - Fn::GetAtt: [ MESHIFYgsheetslookuptableFunction , Arn ]
Outputs:
  MESHIFYgsheetsmodifiedrowFunction:
    Description: '/MESHIFY/MESHIFY/gsheets/modifiedrow/lambda'
    Value:
      Fn::GetAtt: [ MESHIFYgsheetsmodifiedrowFunction , Arn ]
  MESHIFYgsheetsmodifiedrowRole:
    Description: '/MESHIFY/MESHIFY/gsheets/modifiedrow/role'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  MESHIFYgsheetslookuptableFunction:
    Description: '/MESHIFY/MESHIFY/gsheets/lookuptable/lambda'
    Value:
      Fn::GetAtt: [ MESHIFYgsheetsmodifiedrowFunction , Arn ]
  MESHIFYgsheetslookuptableRole:
    Description: '/MESHIFY/MESHIFY/gsheets/lookuptable/role'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
